import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import BackgroundVideo from "../components/BackgroundVideo/BackgroundVideo";
import HotkeyDisplay from "../components/HotkeyDisplay/HotkeyDisplay";
import Spinner from "../components/Spinner/Spinner";
import TypingTest from "../components/TypingTest/TypingTest";
import { useAppStore } from "../hooks/useAppStore";
import { SENTENCE } from "../util/static/static";

/* ==================================================
  Generate random sentence
  Split that into 2D array of [word][chars]
  Render that into the DOM as [span][span]
  Initialize global variables --> wordIndex and charIndex = 0
 
  === USER CONTROLS ===
  Game starts when user hits any alphanumerical key
     Start timer
 
  Any alphanumerical increments charIndex
     if charIndex > 0 --> pressing space button increments wordIndex
 
  This goes on until last character entered matches the last character in the sentence. 
  ================================================== */

const Home: NextPage = () => {
  return (
    <div className="relative h-screen w-screen">
      <Head>
        <title>Thockey.io</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TypingTest />
      <BackgroundVideo />
    </div>
  );
};

export default Home;
